from nomad.datamodel.data import EntryData, Section
from nomad.datamodel.metainfo.annotations import BrowserAdaptors, BrowserAnnotation
from nomad.metainfo import Datetime, Quantity, SchemaPackage

m_package = SchemaPackage()


class OpticalMicroscopy(EntryData):
    """
    An example schema for optical microscopy measurements.
    """

    m_def = Section(
        label='Optical Microscopy',
    )
    data_file = Quantity(
        type=str,
        description='Data file coming from the microscope.',
        a_browser=BrowserAnnotation(adaptor=BrowserAdaptors.RawFileAdaptor),
    )
    datetime = Quantity(
        type=Datetime,
        description='Datetime of the measurement.',
    )
    sample_id = Quantity(
        type=str,
        description='Identifier for the sample used in the measurement.',
    )
    description = Quantity(
        type=str,
        description='Any information that cannot be captured in the other fields.',
    )

    # measurement settings
    resolution = Quantity(
        type=int,
        description='Resolution of the resulting image in terms of pixels.',
        shape=[2],
    )
    magnification = Quantity(
        type=float,
        description='Magnification factor used for the resulting image.',
    )

    # measurement results
    image = Quantity(
        type=str,
        description='Image file generated by the microscope.',
        a_browser=BrowserAnnotation(adaptor=BrowserAdaptors.RawFileAdaptor),
    )


m_package.__init_metainfo__()
